INSERT INTO categories VALUES (1, '    Action Figures');
INSERT INTO categories VALUES (2, '    Advertising');
INSERT INTO categories VALUES (3, '    Agriculture');
INSERT INTO categories VALUES (4, '    Animals');
INSERT INTO categories VALUES (5, '    Antiquarian, Rare');
INSERT INTO categories VALUES (6, '    Antique Prints');
INSERT INTO categories VALUES (7, '    Antiques (post-1900)');
INSERT INTO categories VALUES (8, '    Antiquities');
INSERT INTO categories VALUES (9, '    Apple, Macintosh');
INSERT INTO categories VALUES (10, '    Architectural');
INSERT INTO categories VALUES (11, '    Art, Animation & Photo Images');
INSERT INTO categories VALUES (12, '    Art: Fine');
INSERT INTO categories VALUES (13, '    Asian Antiques');
INSERT INTO categories VALUES (14, '    Audio');
INSERT INTO categories VALUES (15, '    Australia');
INSERT INTO categories VALUES (16, '    Autographs');
INSERT INTO categories VALUES (17, '    Autographs, Paper & Writing');
INSERT INTO categories VALUES (18, '    Aviation');
INSERT INTO categories VALUES (19, '    Baby Items');
INSERT INTO categories VALUES (20, '    Barbie');
INSERT INTO categories VALUES (21, '    Beads, Amulets');
INSERT INTO categories VALUES (22, '    Bears');
INSERT INTO categories VALUES (23, '    Body Art, Tattoos');
INSERT INTO categories VALUES (24, '    Books, Manuscripts');
INSERT INTO categories VALUES (25, '    Boys');
INSERT INTO categories VALUES (26, '    Br. Comm. Other');
INSERT INTO categories VALUES (27, '    Braille');
INSERT INTO categories VALUES (28, '    Building Supplies');
INSERT INTO categories VALUES (29, '    Building Toys');
INSERT INTO categories VALUES (30, '    Businesses for Sale');
INSERT INTO categories VALUES (31, '    Camera Accessories');
INSERT INTO categories VALUES (32, '    Canada');
INSERT INTO categories VALUES (33, '    Candles, Candle Holders');
INSERT INTO categories VALUES (34, '    Car Audio & Electronics');
INSERT INTO categories VALUES (35, '    Ceramics');
INSERT INTO categories VALUES (36, '    Children');
INSERT INTO categories VALUES (37, '    Classic Toys');
INSERT INTO categories VALUES (38, '    Coin-Op, Banks & Casino');
INSERT INTO categories VALUES (39, '    Coins: US');
INSERT INTO categories VALUES (40, '    Coins: World');
INSERT INTO categories VALUES (41, '    Construction');
INSERT INTO categories VALUES (42, '    Cookbooks');
INSERT INTO categories VALUES (43, '    Costume Jewelry');
INSERT INTO categories VALUES (44, '    Costumes');
INSERT INTO categories VALUES (45, '    Cultures & Religions');
INSERT INTO categories VALUES (46, '    Darkroom Equip, Supplies');
INSERT INTO categories VALUES (47, '    Decorative & Holiday');
INSERT INTO categories VALUES (48, '    Designer, Artisan Jewelry');
INSERT INTO categories VALUES (49, '    Desktop Components');
INSERT INTO categories VALUES (50, '    Desktop PCs');
INSERT INTO categories VALUES (51, '    Diecast, Toy Vehicles');
INSERT INTO categories VALUES (52, '    Digital Cameras');
INSERT INTO categories VALUES (53, '    Disneyana');
INSERT INTO categories VALUES (54, '    Doll Clothes, Furniture');
INSERT INTO categories VALUES (55, '    Doll Making, Patterns, Repair');
INSERT INTO categories VALUES (56, '    Dolls');
INSERT INTO categories VALUES (57, '    Domain Names');
INSERT INTO categories VALUES (58, '    Drives, Media');
INSERT INTO categories VALUES (59, '    Education & Learning');
INSERT INTO categories VALUES (60, '    Educational, Developmental');
INSERT INTO categories VALUES (61, '    Electronic Parts');
INSERT INTO categories VALUES (62, '    Electronic, Battery, Wind-Up');
INSERT INTO categories VALUES (63, '    Ethnic, Tribal Jewelry');
INSERT INTO categories VALUES (64, '    Ethnographic');
INSERT INTO categories VALUES (65, '    Europe');
INSERT INTO categories VALUES (66, '    European');
INSERT INTO categories VALUES (67, '    Exonumia');
INSERT INTO categories VALUES (68, '    Fast Food, Advertising');
INSERT INTO categories VALUES (69, '    Fiction');
INSERT INTO categories VALUES (70, '    Film');
INSERT INTO categories VALUES (71, '    Film Cameras');
INSERT INTO categories VALUES (72, '    Fine Jewelry');
INSERT INTO categories VALUES (73, '    First Editions');
INSERT INTO categories VALUES (74, '    Folk Art');
INSERT INTO categories VALUES (75, '    Food & Beverage');
INSERT INTO categories VALUES (76, '    Furnishings, Knives & Tools');
INSERT INTO categories VALUES (77, '    Furniture');
INSERT INTO categories VALUES (78, '    Gadgets & Other Electronics');
INSERT INTO categories VALUES (79, '    Games');
INSERT INTO categories VALUES (80, '    Garden Items');
INSERT INTO categories VALUES (81, '    Genealogy');
INSERT INTO categories VALUES (82, '    General');
INSERT INTO categories VALUES (83, '    General Equipment');
INSERT INTO categories VALUES (84, '    Gifts & Party Supplies');
INSERT INTO categories VALUES (85, '    Girls');
INSERT INTO categories VALUES (86, '    Glass');
INSERT INTO categories VALUES (87, '    Hair Jewelry');
INSERT INTO categories VALUES (88, '    Health & Wellness');
INSERT INTO categories VALUES (89, '    Historical Memorabilia');
INSERT INTO categories VALUES (90, '    Hobbies & Crafts');
INSERT INTO categories VALUES (91, '    Home Audio & Video');
INSERT INTO categories VALUES (92, '    Home Furnishings');
INSERT INTO categories VALUES (93, '    Household Items');
INSERT INTO categories VALUES (94, '    Houses, Miniatures');
INSERT INTO categories VALUES (95, '    Housewares & Kitchenware');
INSERT INTO categories VALUES (96, '    Infants');
INSERT INTO categories VALUES (97, '    Input Peripherals');
INSERT INTO categories VALUES (98, '    Jewelry Boxes');
INSERT INTO categories VALUES (99, '    Jewelry Supplies');
INSERT INTO categories VALUES (100, '    Laboratory Equipment');
INSERT INTO categories VALUES (101, '    Laptops & Accessories');
INSERT INTO categories VALUES (102, '    Large Print');
INSERT INTO categories VALUES (103, '    Latin America');
INSERT INTO categories VALUES (104, '    Lenses');
INSERT INTO categories VALUES (105, '    Loose Gemstones');
INSERT INTO categories VALUES (106, '    Magazines');
INSERT INTO categories VALUES (107, '    Maps, Atlases');
INSERT INTO categories VALUES (108, '    Maritime');
INSERT INTO categories VALUES (109, '    Medical');
INSERT INTO categories VALUES (110, '    Medical, Dental');
INSERT INTO categories VALUES (111, '    Memberships');
INSERT INTO categories VALUES (112, '    Memorabilia');
INSERT INTO categories VALUES (113, '    Men');
INSERT INTO categories VALUES (114, '    Metalware');
INSERT INTO categories VALUES (115, '    Metalworking Equipment');
INSERT INTO categories VALUES (116, '    Metaphysical');
INSERT INTO categories VALUES (117, '    Militaria');
INSERT INTO categories VALUES (118, '    Monitors');
INSERT INTO categories VALUES (119, '    Music Memorabilia');
INSERT INTO categories VALUES (120, '    Musical Instruments');
INSERT INTO categories VALUES (121, '    Networking');
INSERT INTO categories VALUES (122, '    Nonfiction');
INSERT INTO categories VALUES (123, '    Novelties: Risque');
INSERT INTO categories VALUES (124, '    Office Equipment');
INSERT INTO categories VALUES (125, '    Office Furniture');
INSERT INTO categories VALUES (126, '    Office Supplies');
INSERT INTO categories VALUES (127, '    Optics');
INSERT INTO categories VALUES (128, '    Other');
INSERT INTO categories VALUES (129, '    Other Hardware');
INSERT INTO categories VALUES (130, '    Other World');
INSERT INTO categories VALUES (131, '    Outdoor Toys, Structures');
INSERT INTO categories VALUES (132, '    PDAs/Handheld PCs');
INSERT INTO categories VALUES (133, '    Paper Dolls');
INSERT INTO categories VALUES (134, '    Paper Money: US');
INSERT INTO categories VALUES (135, '    Paper Money: World');
INSERT INTO categories VALUES (136, '    Personal Care');
INSERT INTO categories VALUES (137, '    Personal Security');
INSERT INTO categories VALUES (138, '    Pet Supplies');
INSERT INTO categories VALUES (139, '    Philately');
INSERT INTO categories VALUES (140, '    Phones & Wireless Devices');
INSERT INTO categories VALUES (141, '    Poetry');
INSERT INTO categories VALUES (142, '    Pop Culture');
INSERT INTO categories VALUES (143, '    Portable Audio & Video');
INSERT INTO categories VALUES (144, '    Pottery & China');
INSERT INTO categories VALUES (145, '    Pretend Play, Make-Believe');
INSERT INTO categories VALUES (146, '    Primitives');
INSERT INTO categories VALUES (147, '    Printed, Recorded');
INSERT INTO categories VALUES (148, '    Printers & Supplies');
INSERT INTO categories VALUES (149, '    Printing Equipment');
INSERT INTO categories VALUES (150, '    Projection Equipment');
INSERT INTO categories VALUES (151, '    Pulps, Club Editions');
INSERT INTO categories VALUES (152, '    Puzzles');
INSERT INTO categories VALUES (153, '    Radio Equipment');
INSERT INTO categories VALUES (154, '    Reference');
INSERT INTO categories VALUES (155, '    Religious Products & Supplies');
INSERT INTO categories VALUES (156, '    Reproductions');
INSERT INTO categories VALUES (157, '    Restaurant');
INSERT INTO categories VALUES (158, '    Retail');
INSERT INTO categories VALUES (159, '    Reward Points, Incentive Progs');
INSERT INTO categories VALUES (160, '    Robots, Monsters, Space Toys');
INSERT INTO categories VALUES (161, '    Safety and Security');
INSERT INTO categories VALUES (162, '    Scanners');
INSERT INTO categories VALUES (163, '    School Annuals');
INSERT INTO categories VALUES (164, '    Science Instruments');
INSERT INTO categories VALUES (165, '    Science, Medical');
INSERT INTO categories VALUES (166, '    Scripophily');
INSERT INTO categories VALUES (167, '    Services');
INSERT INTO categories VALUES (168, '    Shipping & Packing Supplies');
INSERT INTO categories VALUES (169, '    Show Supplies');
INSERT INTO categories VALUES (170, '    Silver');
INSERT INTO categories VALUES (171, '    Silver Plate');
INSERT INTO categories VALUES (172, '    Software');
INSERT INTO categories VALUES (173, '    Solar Energy');
INSERT INTO categories VALUES (174, '    Sporting Goods');
INSERT INTO categories VALUES (175, '    Stuffed Animals, Beanbag');
INSERT INTO categories VALUES (176, '    Subscriptions');
INSERT INTO categories VALUES (177, '    Swimming Pools');
INSERT INTO categories VALUES (178, '    TV, Character Toys');
INSERT INTO categories VALUES (179, '    Technology Books');
INSERT INTO categories VALUES (180, '    Telephone Systems');
INSERT INTO categories VALUES (181, '    Test Auctions');
INSERT INTO categories VALUES (182, '    Test Equipment');
INSERT INTO categories VALUES (183, '    Textbooks, Education');
INSERT INTO categories VALUES (184, '    Textiles, Linens');
INSERT INTO categories VALUES (185, '    Tickets & Experiences');
INSERT INTO categories VALUES (186, '    Toleware');
INSERT INTO categories VALUES (187, '    Tools');
INSERT INTO categories VALUES (188, '    Topical');
INSERT INTO categories VALUES (189, '    Toy Soldiers');
INSERT INTO categories VALUES (190, '    Trading Cards');
INSERT INTO categories VALUES (191, '    Transportation');
INSERT INTO categories VALUES (192, '    Travel');
INSERT INTO categories VALUES (193, '    UK (Great Britain)');
INSERT INTO categories VALUES (194, '    Uniforms');
INSERT INTO categories VALUES (195, '    United States');
INSERT INTO categories VALUES (196, '    Vehicle Parts, Access. (AFA)');
INSERT INTO categories VALUES (197, '    Vehicles (AFA)');
INSERT INTO categories VALUES (198, '    Video & Multimedia');
INSERT INTO categories VALUES (199, '    Video Games');
INSERT INTO categories VALUES (200, '    Video, Film');
INSERT INTO categories VALUES (201, '    Vintage');
INSERT INTO categories VALUES (202, '    Vintage Clothing, Accessories');
INSERT INTO categories VALUES (203, '    Vintage Paperbacks');
INSERT INTO categories VALUES (204, '    Vintage, Antique Toys');
INSERT INTO categories VALUES (205, '    Watches');
INSERT INTO categories VALUES (206, '    Wedding Apparel');
INSERT INTO categories VALUES (207, '    Weird Stuff');
INSERT INTO categories VALUES (208, '    Wholesale, Large Lots');
INSERT INTO categories VALUES (209, '    Women');
INSERT INTO categories VALUES (210, '    Woodenware');
INSERT INTO categories VALUES (211, '    eBay Stuff');
INSERT INTO categories VALUES (212, 'Antiques & Art');
INSERT INTO categories VALUES (213, 'Books');
INSERT INTO categories VALUES (214, 'Business, Office & Industrial');
INSERT INTO categories VALUES (215, 'Clothing & Accessories');
INSERT INTO categories VALUES (216, 'Coins');
INSERT INTO categories VALUES (217, 'Collectibles');
INSERT INTO categories VALUES (218, 'Computers');
INSERT INTO categories VALUES (219, 'Consumer Electronics');
INSERT INTO categories VALUES (220, 'Dolls & Bears');
INSERT INTO categories VALUES (221, 'Everything Else');
INSERT INTO categories VALUES (222, 'Home & Garden');
INSERT INTO categories VALUES (223, 'Jewelry, Gems & Watches');
INSERT INTO categories VALUES (224, 'Movies & Television');
INSERT INTO categories VALUES (225, 'Music');
INSERT INTO categories VALUES (226, 'Photo');
INSERT INTO categories VALUES (227, 'Pottery & Glass');
INSERT INTO categories VALUES (228, 'Sports');
INSERT INTO categories VALUES (229, 'Stamps');
INSERT INTO categories VALUES (230, 'Tickets & Travel');
INSERT INTO categories VALUES (231, 'Toys & Hobbies');
